@echo off
setlocal

:: ---------------------------------------------------------------------------
:: Branch-specific build output directory.
::
:: This is the master / reshade build line. Each branch builds into its own
:: directory, named after its UEVR_VARIANT_ID, so the variants never share a
:: CMake cache or intermediate objects. Do not point this at the in-tree
:: build\ directory.
:: ---------------------------------------------------------------------------
set "BUILDDIR=A:\UEVR-build\reshade"
if not exist "%BUILDDIR%" mkdir "%BUILDDIR%"

:: Find cmake: prefer PATH, fall back to local VS 2026 install
where cmake >nul 2>&1
if %ERRORLEVEL% equ 0 (
    set "CMAKE=cmake"
) else (
    set "CMAKE=C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"
)

:: Configure if build dir doesn't exist yet (auto-detect generator)
:: NOTE: use `if errorlevel 1`, not `if %ERRORLEVEL% neq 0`. Inside a
:: parenthesised block cmd expands %ERRORLEVEL% when it parses the block, i.e.
:: before cmake has run, so the check would test a stale value.
if not exist "%BUILDDIR%\CMakeCache.txt" (
    echo Configuring CMake into %BUILDDIR% ...
    "%CMAKE%" -S . -B "%BUILDDIR%" -A x64 -DCMAKE_BUILD_TYPE=Release
    if errorlevel 1 (
        echo CONFIGURE FAILED
        exit /b 1
    )
)

:: Regenerate commit hash (delete stale file so CMake pre-build step recreates it)
if exist "src\CommitHash.autogenerated" del /f "src\CommitHash.autogenerated"

:: ---------------------------------------------------------------------------
:: Stale-.obj guard.
::
:: MSBuild's incremental dependency tracking does not always recompile a .cpp
:: when a header it includes has changed, particularly when the change adds a
:: field to a struct used across DLL boundaries. The result is an ABI mismatch
:: at runtime (one TU sees the new struct layout, another sees the old) which
:: surfaces as silent data corruption with no compile / link / build error.
:: See COMPILING.md "Build-system gotchas" for the full postmortem.
::
:: Strategy: if any header inside a watched directory has been modified more
:: recently than the oldest .obj in the matched intermediate dir, delete ALL
:: .obj files in that intermediate dir. MSBuild then has no choice but to
:: recompile the affected translation units this run. We over-delete (e.g. we
:: also drop imgui_impl_*.obj when only effect_runtime.hpp changed) — that's
:: deliberately safe; renderlib is small (~10 TUs) and rebuilds in seconds.
::
:: Watched pairs: <header dir (recursive)> -> <intermediate obj dir>.
:: Add new pairs here when introducing new cross-DLL public headers.
:: ---------------------------------------------------------------------------
echo Checking for stale object files vs. modified headers...
call powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0scripts\check_stale_objs.ps1" -BuildDir "%BUILDDIR%"
if %ERRORLEVEL% neq 0 echo Stale-obj guard failed; continuing build.

echo Building UEVR + plugins (Release)...
"%CMAKE%" --build "%BUILDDIR%" --config Release
if errorlevel 1 (
    echo BUILD FAILED
    exit /b 1
)

echo.
echo Build succeeded (%BUILDDIR%).
