@echo off
setlocal

:: ---------------------------------------------------------------------------
:: Branch-specific build output directory.
::
:: This is the wyerdev/afw-joeyhodge integration branch
:: (upstream: PureDark/UEVR:Joey-Merged = AFW + joeyhodge/UEVR:ue57performance).
:: Each branch builds into its own directory, named after its UEVR_VARIANT_ID,
:: so the variants never share a CMake cache or intermediate objects. Do not
:: point this at the in-tree build\ directory.
::
:: Overridable via UEVR_BUILD_DIR. CI has no A: drive, so a release workflow
:: must set it to the in-tree build\ dir that its artifact steps glob. Never
:: hardcode a local-only path here without leaving this escape hatch.
:: ---------------------------------------------------------------------------
if defined UEVR_BUILD_DIR (
    set "BUILDDIR=%UEVR_BUILD_DIR%"
) else (
    set "BUILDDIR=A:\UEVR-build\afw-joeyhodge"
)
if not exist "%BUILDDIR%" mkdir "%BUILDDIR%"
if not exist "%BUILDDIR%" (
    echo BUILD DIR UNAVAILABLE: %BUILDDIR%
    echo Set UEVR_BUILD_DIR to a writable path.
    exit /b 1
)

:: Find cmake: prefer PATH, fall back to local VS 2026 install
where cmake >nul 2>&1
if %ERRORLEVEL% equ 0 (
    set "CMAKE=cmake"
) else (
    set "CMAKE=C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"
)

:: Configure if build dir doesn't exist yet (auto-detect generator)
:: NOTE: use `if errorlevel 1`, not `if %ERRORLEVEL% neq 0`. Inside a
:: parenthesised block cmd expands %ERRORLEVEL% when it parses the block, i.e.
:: before cmake has run, so the check would test a stale value.
if not exist "%BUILDDIR%\CMakeCache.txt" (
    echo Configuring CMake into %BUILDDIR% ...
    "%CMAKE%" -S . -B "%BUILDDIR%" -A x64 -DCMAKE_BUILD_TYPE=Release
    if errorlevel 1 (
        echo CONFIGURE FAILED
        exit /b 1
    )
)

:: ---------------------------------------------------------------------------
:: [2026-07-31] One step from the other build lines is deliberately absent:
:: the stale-.obj guard. scripts\check_stale_objs.ps1 does not exist on this
:: branch, and its watched header/intermediate pairs are the shader renderlib
:: ones. Port it together with the shader work, not before.
::
:: Commit-hash generation needs no help here: this branch drives it from a
:: CMake pre-build step ("Generating commit hash..."), so unlike the other
:: lines there is no stale src\CommitHash.autogenerated to delete first.
:: ---------------------------------------------------------------------------

echo Building UEVR (Release)...
"%CMAKE%" --build "%BUILDDIR%" --config Release
if errorlevel 1 (
    echo BUILD FAILED
    exit /b 1
)

echo.
echo Build succeeded (%BUILDDIR%).
