@echo off
setlocal enabledelayedexpansion

FOR /F "tokens=*" %%g IN ('git rev-parse HEAD') DO (SET UEVR_COMMIT_HASH=%%g)

FOR /F "tokens=*" %%t IN ('git describe --tags --always --abbrev^=0') DO (SET UEVR_TAG=%%t)
IF "%UEVR_TAG%"=="" (SET UEVR_TAG=no_tag)

FOR /F "tokens=*" %%d IN ('git describe --tags --always --long') DO (
    set "src=%%d"
    set cnt=0
    for %%i in ("!src:-=" "!") do (
        set /a cnt+=1
    )
	if !cnt!==3 (
		FOR /F "tokens=1,2 delims=-" %%a IN ("%%d") DO (
			SET UEVR_TAG_LONG=%%a
			SET UEVR_COMMITS_PAST_TAG=%%b
		)
	)
	if !cnt!==4 (
		FOR /F "tokens=1,2,3 delims=-" %%a IN ("%%d") DO (
			SET UEVR_TAG_LONG=%%a-%%b
			SET UEVR_COMMITS_PAST_TAG=%%c
		)
	)
)

IF "%UEVR_COMMITS_PAST_TAG%"=="" (SET UEVR_COMMITS_PAST_TAG=0)

FOR /F "tokens=*" %%b IN ('git rev-parse --abbrev-ref HEAD') DO (SET UEVR_BRANCH=%%b)

FOR /F "tokens=*" %%n IN ('git rev-list --count HEAD') DO (SET UEVR_TOTAL_COMMITS=%%n)
IF "%UEVR_TOTAL_COMMITS%"=="" (SET UEVR_TOTAL_COMMITS=0)

FOR /F "tokens=*" %%a IN ('powershell -NoProfile -Command "Get-Date -Format yyyyMMddHHmmss"') DO (
SET datetime=%%a
)

SET year=%datetime:~0,4%
SET month=%datetime:~4,2%
SET day=%datetime:~6,2%
SET hour=%datetime:~8,2%
SET minute=%datetime:~10,2%

echo #pragma once > src/CommitHash.autogenerated
echo #define UEVR_COMMIT_HASH "%UEVR_COMMIT_HASH%" >> src/CommitHash.autogenerated
echo #define UEVR_TAG "%UEVR_TAG%" >> src/CommitHash.autogenerated
echo #define UEVR_TAG_LONG "%UEVR_TAG_LONG%" >> src/CommitHash.autogenerated
echo #define UEVR_COMMITS_PAST_TAG %UEVR_COMMITS_PAST_TAG% >> src/CommitHash.autogenerated
echo #define UEVR_BRANCH "%UEVR_BRANCH%" >> src/CommitHash.autogenerated
echo #define UEVR_TOTAL_COMMITS %UEVR_TOTAL_COMMITS% >> src/CommitHash.autogenerated
echo #define UEVR_BUILD_DATE "%day%.%month%.%year%" >> src/CommitHash.autogenerated
echo #define UEVR_BUILD_TIME "%hour%:%minute%" >> src/CommitHash.autogenerated
